# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

#### 1. Import NumPy as np

In [66]:
import numpy as np

hello


#### 2. Create an array of 10 zeros

In [95]:
# CODE HERE
arr = np.zeros(10,dtype = int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
# DON'T WRITE HERE

#### 3. Create an array of 10 ones

In [99]:
one = np.ones(10, dtype = int)
one

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [69]:
# DON'T WRITE HERE

#### 4. Create an array of 10 fives

In [102]:
five = np.full(10,5)
five

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [70]:
# DON'T WRITE HERE

#### 5. Create an array of the integers from 10 to 50

In [106]:
tenToFifty = np.arange(10,51,1)
tenToFifty

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [71]:
# DON'T WRITE HERE

#### 6. Create an array of all the even integers from 10 to 50

*   List item
*   List item



In [108]:
even = np.arange(10,51,2)
even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [72]:
# DON'T WRITE HERE

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

1.   List item
2.   List item



In [115]:
myMat = np.arange(0,9,1)
myMat.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
# DON'T WRITE HERE

#### 8. Create a 3x3 identity matrix

In [117]:
iden = np.eye(3,3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
# DON'T WRITE HERE

#### 9. Use NumPy to generate a random number between 0 and 1<br><br>&emsp;NOTE: Your result's value should be different from the one shown below.

In [150]:
np.random.uniform(0,1)

0.3560472960310681

In [124]:
# DON'T WRITE HERE

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution<br><br>&emsp;&ensp;NOTE: Your result's values should be different from the ones shown below.

In [164]:
norDis = np.random.rand(25)
norDis

array([0.00452791, 0.58814028, 0.2927299 , 0.09184725, 0.10697052,
       0.86792194, 0.2155544 , 0.13641157, 0.27369534, 0.65630896,
       0.47280641, 0.75505978, 0.42575269, 0.15745998, 0.0548067 ,
       0.45030312, 0.03078282, 0.17227618, 0.13004738, 0.53772205,
       0.93873467, 0.71562014, 0.86308451, 0.54640752, 0.53968074])

In [76]:
# DON'T WRITE HERE

#### 11. Create the following matrix:

In [77]:
# DON'T WRITE HERE

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [177]:
lineSpac = np.linspace(0,1,20)
lineSpac

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [173]:
# DON'T WRITE HERE

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs:

In [178]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code that reproduces the output shown below.<br><br>&emsp;&ensp;Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.

In [80]:
# CODE HERE


In [81]:
# DON'T WRITE HERE

#### 14. Write code that reproduces the output shown below.

In [82]:
# DON'T WRITE HERE

#### 15. Write code that reproduces the output shown below.

In [83]:
# DON'T WRITE HERE

#### 16. Write code that reproduces the output shown below.

In [84]:
# DON'T WRITE HERE

#### 17. Write code that reproduces the output shown below.

In [85]:
# DON'T WRITE HERE

## NumPy Operations

#### 18. Get the sum of all the values in mat

In [184]:
ans = 0
for i in range (5):
    for j in range(5):
        ans+= mat[i][j]
    
print(ans)

325


In [185]:
matSum = np.sum(mat)
matSum

325

In [86]:
# DON'T WRITE HERE

#### 19. Get the standard deviation of the values in mat

In [186]:
stdDev = np.std(mat)
stdDev

7.211102550927978

In [87]:
# DON'T WRITE HERE

#### 20. Get the sum of all the columns in mat

In [88]:
# DON'T WRITE HERE

In [192]:
rowSum = np.sum(mat,axis = 0)
rowSum

array([55, 60, 65, 70, 75])

In [193]:
colSum = np.sum(mat,axis = 1)
colSum

array([ 15,  40,  65,  90, 115])

## Bonus Question
We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers? What does the seed value mean? Does it matter what the actual number is? [Click Here for a Hint](https://www.google.com/search?q=numpy+random+seed)

# Great Job!